# Generated by Django 2.2.7 on 2019-11-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, default=1, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(default='', max_length=200, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('users', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loginapp.Group', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
